FROM python:3.7

RUN apt-get update 
RUN apt-get install -y docker.io

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./racer.py /app/racer.py

ENTRYPOINT [ "python" ]

CMD [ "racer.py" ]