FROM python:3.7

RUN apt-get update 
RUN apt-get install -y docker.io

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY ./input.txt /app/input.txt
COPY ./master.py /app/master.py

ENTRYPOINT [ "python" ]

CMD [ "master.py" ]
